name: Abdelaziz Ibrahim - Docker Image 
on:
  workflow_dispatch:


jobs:
  run-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_SERVER }}/${{ secrets.DOCKER_USERNAME }}/Abdelaziz_Ibrahim:v1.0
        
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }}--password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: docker push ${{ secrets.DOCKER_SERVER }}/${{ env.DOCKER_USERNAME }}/Abdelaziz_Ibrahim:v1.0
  deploy:
    needs: run-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 ${{ secrets.DOCKER_SERVER }}/${{ env.DOCKER_USERNAME }}/Abdelaziz_Ibrahim:v1.0




    
     

