name: Run Docker Image Manually
on: 
  workflow_dispatch:

jobs:
  run-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull abdelazizibrahim/abdelazizim:v1

      - name: Run Docker Container
        run: docker run --rm abdelazizibrahim/abdelazizim:v1
      
      - name: stop container after 2 minutes
        run: |
          sleep 120
          docker ps -q --filter "ancestor=abdelazizibrahim/abdelazizim:v1" | xargs -r docker stop
        continue-on-error: true
